export const FETCH_RESULTS = "FETCH_RESULTS";
export const SAVE_DEFINITION = "SAVE_DEFINITION ";
export const REMOVE_DEFINITION = "REMOVE_DEFINITION";
export const SHOW_BAR = "SHOW_BAR";
export const HIDE_BAR = "HIDE_BAR";
